stack_overflow_analytics:
  outputs:
    dev:
      dataset: stack_overflow_analytics
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: C:\Users\ethan\.dbt\stack_overflow_analytics.json
      location: US
      method: service-account
      priority: interactive
      project: 	silent-grid-482519-d4
      threads: 1
      type: bigquery
  target: dev
